const STANZE =[
    {
        id:'00001a',
        descrizione:"Benvenuto Alleneide, nella sezione di creazione PG. Tutto inizia con una piccola Avventura, ciò permettera di assegnarti la Tribù che più ti si addice... Che l' astro ti sia di favore" ,
        rispostaA:'comiminciamo',
        tribuA:'servizio',
        idsuccA:'00001b',
        rispostaB:'',
        idsuccB:'servizio',
        tribuB:'00001b',
        rispostaC:'',
        tribuC:'servizio',
        idsuccC:'00001b',
        tribuD:'servizio',
        idsuccD:'00001b',
        tribuE:'servizio',
        idsuccE:'00001b',
    },
    {
        id:'00001b',
        descrizione:"Se l'Astro volesse mai concedermi un beneficio, mi salverebbe da tutto ciò. \n Lentamente il mio corpo sembra risvegliarsi da un antico torpore,non riesco bene a capire se ho gli occhi aperti o continuano a restare chiusi, l'Oscurità, il Kel, come con riverenza è chiamata dalle genti dell’Alleneis, mi circonda, in una coltre cosi spessa che pare materia.\n Lo stomaco non mi da tregua, mentre le ossa e i muscoli sembrano bloccati, congelati dall'umidità, che li ha invasi mentre dormivo disteso su questo pavimento gelato;\n ma più di ogni altra cosa in questo momento soffro l'arsura.\n Cosa darei per un piccolo sorso d'acqua.\n La testa è pesante, non riesco a raccogliere bene i pensieri e persino i ricordi mi risultano difficili.\n Qualunque luogo sia questo in cui mi trovo, devo reagire, prima che perda anche l'ultimo barlume di ragione.",
        rispostaA:'Con sofferenza, cerco di destare le braccia sopite, allungandole alla ricerca di qualsiasi cosa mi circondi, ho bisogno di tastare qualcosa per sapere che non sto dormendo.',
        tribuA:'Kumpania',
        idsuccA:'00001c',
        rispostaB:"Cerco di raccogliere i miei pensieri, affrontando  Il Kel con i miei sensi, l'udito è perfetto per rubare al silezio il più piccolo indizio.",
        idsuccB:'00001d',
        tribuB:'Kumpania',
        rispostaC:"Devo raccogliere nelle mie gambe tutto il mio coraggio, prima che la paura mi afferri il cuore; di scatto mi sollevo:-' se la morte è ciò che mi aspetta, mi troverà retto'-.",
        tribuC:'Brennen',
        idsuccC:'00001e',
        rispostaD:'',
        tribuD:'servizio',
        idsuccD:'00001b',
        rispostaE:'',
        tribuE:'servizio',
        idsuccE:'00001b',
    },
    {
        id:'00001c',
        descrizione:'Le mie mani si muovono frentetiche, come piccole formiche,\nestenzioni della mia orba vista scandagliano il poco spazio che sono in grado di raggiungere, alla ricerca di una speranza a cui aggrapparmi.\n\nLe unghie  ormai dolenti, incontrano una sporgenza, liscia, levigata, dalla forma aguzza, che pare incline a lasciarsi prendere, docile,  come se non avesse altro scopo che appartenermi.\n\nAfferro avido questo sasso, scoprendone un lato ancora affilato,\ncon cura lo porto al mio grembo.\n\nCosa sono diventato, che desidero un sasso, quanto una mela per sazziarmi o un otre per dissetarmi.',
        rispostaA:"Stringo le mani attorno al sasso, vorace delle certezze che mi dona la fredda materia, mentre l'udito cerca di indagare il silezio che mi circonda.",
        tribuA:'Kumpania',
        idsuccA:'00002d',
        rispostaB:"Il gelo di questo pavimento mi entra nello spiritio, prima che gli arti ne restino vittima, devo alzarmi.",
        idsuccB:'00002e',
        tribuB:'Brennen',
        rispostaC:"Deve esserci di più, lentamente mi giro supino, strisciando lentamente, per permettere alle mie braccia di superare quanto gia toccato.",
        tribuC:'Volkron',
        idsuccC:'00002c',
        rispostaD:'',
        tribuD:'servizio',
        idsuccD:'00001c',
        rispostaE:'',
        tribuE:'servizio',
        idsuccE:'00001c',
    },
    {
        id:'00002c',
        descrizione:"Strisciare mi duole , le lastre iregolari e mal poste, che compongono il pavimento, mi straziano, lasciandomi graffiato e rantolante, mentre , lo stomaco a contatto con il gelo del suolo pare aumentare i morsi della fame.\nLe braccia si allungano ancora cercando rapide di carpire quante più informazioni possibili.\nUna, di colpo, pare cadere in una piccola polla di un liquido caldo e denso, sul cui fondo sembra esseci qualcosa di piccolo e affusolato, incastrato tra le rocce.\nimmediatamente porto la mano alla bocca, e con sgomento, il sapore mi conferma ciò che la mente aveva potuto solo temere, sangue, frammisto a terra, riempie una piccola buca.\n\nTrattengo a forza lo stomaco, quando con fare veloce immergo nuovamente la mano nella pozza, speranzoso ne recupero il tesoro sommerso.\nAl tatto si presenta morbido , con delle parti dure internamente e una piccola superfice liscia anche essa dura su una delle sommità;\nUn sobbalzo mi porta ad allontarmi buttandomi alle spalle, quello che aveva tutta l'aria di essere un dito mozzato.\nLa mia paura deve aver destato qualcosa, un  rumore alieno, di qualcosa che si dimena rapido sbattendo vigorso , spezza il silenzio assordante del Kel, probabilmente proviene da sopra la mia testa;\nC'è qualcosa di vivo oltre me in questo luogo; ",
        rispostaA:"Devo raccogliere nelle mie gambe tutto il mio coraggio, prima che la paura mi afferri il cuore; di scatto mi sollevo:-' se la morte è ciò che mi aspetta, mi troverà retto'-.",
        tribuA:'Brennen',
        idsuccA:'00001e',
        rispostaB:"Cerco di raccogliere i miei pensieri, affrontando  Il Kel con i miei sensi, l'udito è perfetto per rubare al silezio il più piccolo indizio.",
        idsuccB:'00001d',
        tribuB:'Kumpania', 
        rispostaC:"-'Che l'Astro non mi neghi ancora la sorte, lasciandomi  colpire ciò che produce quel maledetto ronzio'-, cercando tutta la forza rimasta, scaglio il mio bene più prezioso, in direzione del soffitto.",
        tribuC:'Kumpania',
        idsuccC:'00003c',
        rispostaD:'',
        tribuD:'servizio',
        idsuccD:'00002c',
        rispostaE:'',
        tribuE:'servizio',
        idsuccE:'00002c',
    },
    {
        id:'00003c',
        descrizione:"il bicipite flette, la mano si apreal termine della corsa del braccio, sperando che la fortuna mi arrida.\nIl sasso diparte dalla mano e per aluni interminabili istanti il silenzio fa da padrone nella stanza.\nUn rumore tonfo mi colpisce dritto al cuore, qualcosa è stato colpito,che sia un soffitto , una parete o la causa del ronzio solo il Kel lo sa.\nLa speranza pero  mi ringonfia il petto, il silenzio in cui tutto e ricaduto mi fa immaginare di aver colpito qualsiasi cosa ci fosse nella stanza.\nraccolgo le gambe e aiutandomi con le braccia, mi sollevo.\nLe gambe mi reggono a malapena, la testa dolende è preda alle vertigini mentre lo stomaco rantola borioso;\nd'improvviso  il  ronzio riprende, sempre più acuto e rapido.\nSento la Paura ghermire il mio cuore, non posso permetterlo, raccolgo nella gola secca le ultime parole, in un grido tordo, che sfidi l'abisso.\nIl ronzio pare placarsi all'istante;\nUna lenta aurea iridescente, dai colori del fuoco, colpisce i miei occhi stanchi, dalla sommita di quella che finalmente mi appare come una stanza;\nil Ronzio riprende in tutta la sua maesta, mentre\nvia via che la mia vista recupera il suo vigore, si delinea la forma di una grossa falena dal dorso luminoso come il fuoco, che veloce vola verso di me.",
        rispostaA:"il mio corpo si specchia, nei migliaia di occhi di questa falena, mentre con la forza della disperazione provo a spingermi oltre il limite impostomi dalla fatica, supplicando le mie sfinite gambe di schivare all'ultimo, per colpire la carogna con tutta la forza rimastami nelle braccia.",
        tribuA:'Brennen',
        idsuccA:'10000e',
        rispostaB:"Posso solo chiudermi tra le braccia, cercando di offrire alla falena quanto meno di me possibile, mentre distolgo lo sguardo, inorridendo alla vista del mio infausto destino",
        idsuccB:'00004e',
        tribuB:'Popolo di zao', 
        rispostaC:'mi raggelo, impietrito, sperando che qualsiasi cosa abbia provocato il suono non mi noti, ma non posso fare a meno di continuare ad ascoltare quanto accade intorno a me',
        tribuC:'Kumpania',
        idsuccC:'00005e',
        rispostaD:'',
        tribuD:'servizio',
        idsuccD:'00003c',
        rispostaE:'',
        tribuE:'servizio',
        idsuccE:'00003c',
    },
    {
        id:'00001d',
        descrizione:"Resto immobile nella posizione fetale in cui sono racchiuso su questo pavimento gelido, cercando di concentrarmi su i suoni che mi circondano.\n\nD'apprima nulla sembra rompere il silenzio stagnate di questo luogo;\n\nProprio quando sto per perdere la speranza, il suono tondo di una goccia d'acqua che cade nello specchio di quello che potrebbe essere una pozzanghera, irrompe.\n\nUn rapido frastuono, sembra risvegliarsi, qualcosa che struscia dibattendendosi pare provenire dalla sommita dell'oscurita in cui mi trovo;\n\n NON SONO SOLO...",
        rispostaA:"Con sofferenza, cerco di destare le braccia sopite, allungandole alla ricerca di qualsiasi cosa mi circondi, di qualcosa che possa difendermi",
        tribuA:'Volkron',
        idsuccA:'00002c',
        rispostaB:"Devo raccogliere nelle mie gambe tutto il mio coraggio, prima che la paura mi afferri il cuore; di scatto mi sollevo:-' se la morte è ciò che mi aspetta, mi troverà retto'-.",
        idsuccB:'00002e',
        tribuB:'Brennen', 
        rispostaC:'mi raggelo, impietrito, sperando che qualsiasi cosa abbia provocato il suono non mi noti, ma non posso fare a meno di continuare ad ascoltare quanto accade intorno a me',
        tribuC:'Kumpania',
        idsuccC:'00003d',
        rispostaD:'',
        tribuD:'servizio',
        idsuccD:'00001d',
        rispostaE:'',
        tribuE:'servizio',
        idsuccE:'00001d',
    },
    {
        id:'00003d',
        descrizione:"Il ronzio di quanto mi sovrasta continua incessante, mentre l'udito va via via riprendendo vigore, come svegliatosi da una antica paralisi.\nIl Kel inizia a riempirsi d ivita, migliaia di voci parlano all'unisono, in una perfezione che raggela il sangue.\nLe voci non sono nitide, distanti, non riesco a distingure con esattezza le parole pronunciate.\nMentre il ronzio pare volteggiare in circolo sulla mia testa.\nProbabilemente non conosco nemmeno la lingua in cui queste parlano o comunque in questo momento non la rammento.\nAdesso che l'ascolto da un pò però, mi sembra, credo, anzi no, no, sono convinto sia parte di un RItuale, riesco a distinguerne la parte invocativa, inizia infatti sempre con un cambio tono.",
        rispostaA:"Con sofferenza, cerco di destare le braccia sopite, allungandole alla ricerca di qualsiasi cosa mi circondi, di qualcosa che possa difendermi",
        tribuA:'Kumpania',
        idsuccA:'10000d',
        rispostaB:"",
        idsuccB:'00003d',
        tribuB:'servizio', 
        rispostaC:'',
        tribuC:'servizio',
        idsuccC:'00003d',
        rispostaD:'',
        tribuD:'servizio',
        idsuccD:'00003d',
        rispostaE:'',
        tribuE:'servizio',
        idsuccE:'00003d',
    },
    {
        id:'10000d',
        descrizione:"il canto rituale si solevva dal pavimento gelato, aumentando di intensita ad ogni strofa.\nLinee dorate iniziano ad inscriversi tra le fughe  dei grossi sassi che costituiscono la pavimentazione, rischiarando di un'aureaa luce soffussa, l'oscurita tetra della stanza.\nGli occhi impiegano un po ad abbituarsi alla luce, costringendomi ad aprirli e chiuderli velocemente.\nIn quei pochi momenti in cui gli occhi sono aperti, la luce si frammista a miriadi di colori, e mi sembra di notare un immenso serpente dalle scaglie di vetro, muoversi e circondarmi con le sue spire...\nOra lo posso sentire, posso sentire il freddo del suo corpo, e la forza dei suoi muscoli, inizia lentamente e dolcemente a stritolarmi... sono inerme, ma non ho paura...\nIl canto ormai e al suo climax, le parole prima poco chiare, adesso sembrano avere il senso di un antica messa  in onore di quello che ha tutti gli aspetti di un antico Dio...\nL'enorme serpente di cristallo solleva la testa, fissandomi con i suoi occhi vitrei, mentre gli occhi ormai si sono abbituati alla luce e fanno difficolta a distinguerlo dal resto della stanza.\nD'un tratto il Canto si stoppa, ed il serpente scatta famelico spalancando l'inrefrenabile mandibola...\nil dolore è assurdo, ma dura pochi istanti, nella mente mi risuona l'ultima parola del canto... Mezef.. chi sa a cosa si riferisce... \nLentamente tutto diviene buio...",
        rispostaA:"Termina",
        tribuA:'Result',
        idsuccA:'10000d',
        rispostaB:"",
        idsuccB:'10000d',
        tribuB:'servizio', 
        rispostaC:'',
        tribuC:'servizio',
        idsuccC:'10000d',
        rispostaD:'',
        tribuD:'servizio',
        idsuccD:'10000d',
        rispostaE:'',
        tribuE:'servizio',
        idsuccE:'10000d',
    },
    {
        id:'00001e',
        descrizione:"Stringo i denti, nonostante il dolore sordo, raccolgo le gambe e aiutandomi con le braccia, mi sollevo.\n\nLe gambe mi reggono a malapena, la testa dolende è preda alle vertigini mentre lo stomaco rantola borioso;\ntutto sembra impossibile in questo moemento.\nUn incessante ronzio, sempre più acuto e rapido, riempie il silenzio del Kel.\nSento la Paura ghermire il mio cuore, non posso permetterlo, raccolgo nella gola secca le ultime parole, in un grido tordo, che sfidi l'abisso.\nIl ronzio pare placarsi all'istante;\n\nUna lenta aurea iridescente, dai colori del fuoco, colpisce i miei occhi stanchi, dalla sommita di quella che finalmente mi appare come una stanza;\n\nil Ronzio riprende in tutta la sua maesta, mentre via via che la mia vista recupera il suo vigore, si delinea la forma di una grossa falena dal dorso luminoso come il fuoco, che veloce vola verso di me.",
        rispostaA:"il mio corpo si specchia, nei migliaia di occhi di questa falena, mentre con la forza della disperazione provo a spingermi oltre il limite impostomi dalla fatica, supplicando le mie sfinite gambe di schivare all'ultimo, per colpire la carogna con tutta la forza rimastami nelle braccia.",
        tribuA:'Brennen',
        idsuccA:'10000e',
        rispostaB:"Posso solo chiudermi tra le braccia,cercando di offrire alla falena quanto meno di me possibile, mentre distolgo lo sguardo, inorridendo alla vista del mio infausto destino",
        idsuccB:'00004e',
        tribuB:'Popolo di zao', 
        rispostaC:'mi raggelo, impietrito, sperando che qualsiasi cosa abbia provocato il suono non mi noti, ma non posso fare a meno di continuare ad ascoltare quanto accade intorno a me',
        tribuC:'Kumpania',
        idsuccC:'00005e',
        rispostaD:'',
        tribuD:'servizio',
        idsuccD:'00001e',
        rispostaE:'',
        tribuE:'servizio',
        idsuccE:'00001e',
    },

]
export {STANZE};